Use non-default keyring for GPG keys.

diff --git a/gpgutils/gpgdeletepubkey.sh.in b/gpgutils/gpgdeletepubkey.sh.in
--- a/gpgutils/gpgdeletepubkey.sh.in
+++ b/gpgutils/gpgdeletepubkey.sh.in
@@ -7,11 +7,14 @@
 GPG_BIN="/usr/bin/gpg"
 GPG2_BIN="/usr/bin/gpg2"
 
+GPG_KEYRING="@GPG_KEYRING@"
+GPG_SEC_KEYRING="@GPG_SEC_KEYRING@"
+
 function gpg_delete_pub_key ()
 {
 	recipient="$1"
 
-	$GPG_BIN --batch --delete-key --yes "$recipient"
+	$GPG_BIN --batch --keyring "$GPG_KEYRING" --secret-keyring "$GPG_SEC_KEYRING" --no-default-keyring --delete-key --yes "$recipient"
 	return $?
 }
 
@@ -19,7 +22,7 @@ function gpg2_delete_pub_key ()
 {
 	recipient="$1"
 
-	$GPG2_BIN --batch --delete-key --yes "$recipient"
+	$GPG2_BIN --batch --keyring "$GPG_KEYRING" --secret-keyring "$GPG_SEC_KEYRING" --no-default-keyring --delete-key --yes "$recipient"
 	return $?
 }
 
@@ -29,6 +32,11 @@ if [ $# -lt 1 ]; then
 fi
 
 recipient="$1"
+
+if [ ! -e "$GPG_KEYRING" ]; then
+	echo "$0: keyring '$GPG_KEYRING' not found"
+	exit 1
+fi
 
 if [ -x $GPG2_BIN ]; then
 	gpg2_delete_pub_key "$recipient"
diff --git a/gpgutils/gpgimport.sh.in b/gpgutils/gpgimport.sh.in
--- a/gpgutils/gpgimport.sh.in
+++ b/gpgutils/gpgimport.sh.in
@@ -7,17 +7,25 @@
 GPG_BIN="/usr/bin/gpg"
 GPG2_BIN="/usr/bin/gpg2"
 
+GPG_KEYRING="@GPG_KEYRING@"
+GPG_SEC_KEYRING="@GPG_SEC_KEYRING@"
+
 function gpg_import ()
 {
-	cat | $GPG_BIN --batch --import
+	cat | $GPG_BIN --batch --keyring "$GPG_KEYRING" --secret-keyring "$GPG_SEC_KEYRING" --no-default-keyring --import
 	return $?
 }
 
 function gpg2_import ()
 {
-	cat | $GPG2_BIN --batch --import 
+	cat | $GPG2_BIN --batch --keyring "$GPG_KEYRING" --secret-keyring "$GPG_SEC_KEYRING" --no-default-keyring --import
 	return $?
 }
+
+if [ ! -e "$GPG_KEYRING" ]; then
+	echo "$0: keyring '$GPG_KEYRING' not found"
+	exit 1
+fi
 
 if [ -x $GPG2_BIN ]; then
 	gpg2_import 
